version: '3'
services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/var/www/
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: postgres:12.0-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_login
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - backend

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
    depends_on:
      - laravel
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:
    driver: bridge
