version: '3'
services:
  laravel:
    restart: always
    build: .
    volumes:
      - ./:/var/www/
    depends_on:
      - postgres

  postgres:
    image: postgres:12.0-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_login
    volumes:
      - "./.docker/dbdata:/var/lib/postgresql/data"
    ports:
      - 5432:5432

  nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
    depends_on:
      - laravel

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    depends_on:
      - postgres